OrdererOrgs:
  - Name: Orderer
    Domain: mypher.org
    CA:
        Country: JP
        Province: Tokyo
        Locality: Koto
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.mypher.org
    #Template:
    #    Count: 1
    #Users:
    #    Count: 1

  - Name: Org2
    Domain: org2.mypher.org
    #Template:
    #    Count: 1
    #Users:
    #    Count: 1

