version: '2'

services:
  ca.mypher.org:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.mypher.org
    ports:
      - "7054:7054"
    volumes:
      - ./ca_home/:/etc/hyperledger/fabric-ca-server
      - ./keys/crypto-config/ca/:/etc/hyperledger/fabric-ca-server-config
    working_dir: /etc/hyperledger/fabric-ca-server
    command: bash -c './init.sh'
    container_name: ca.mypher.org

  orderer.mypher.org:
    container_name: orderer.mypher.org
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=orderer.mypher.org
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=mypher.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - GRPC_TRACE=all,
      - GRPC_VERBOSITY=debug
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./keys/orderer1:/etc/hyperledger/msp
      - ./tx/mypher.block:/etc/hyperledger/fabric/mypher.block
    ports:
      - 7050:7050

