version: '2'

services:

  peer0.org2.mypher.org:
    container_name: peer0.org2.mypher.org
    image: hyperledger/fabric-peer
    environment:
      - GOPATH=/opt/gopath
      - CORE_PEER_ID=peer0.org2.mypher.org
      - CORE_PEER_ADDRESS=peer0.org2.mypher.org:7051
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.mypher.org:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - GRPC_TRACE=all,
      - GRPC_VERBOSITY=debug
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_ADDRESSAUTODETECT=true
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/:/opt/gopath/src/github.com/mypher/chaincode
        - ./keys/crypto-config/peerOrganizations/org2.mypher.org/users/Admin@org2.mypher.org/msp:/etc/hyperledger/msp
        - ../:/opt/gopath/src/github.com/mypher/peer
    working_dir: /opt/gopath/src/github.com/mypher/peer
    command: peer node start -o orderer.mypher.org:7050
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
      - orderer.mypher.org
